# Generated by Django 5.0.2 on 2024-02-12 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_first_name', models.CharField(max_length=100)),
                ('emp_last_name', models.CharField(max_length=100)),
                ('emp_role', models.IntegerField(default=0)),
                ('emp_id', models.CharField(max_length=200)),
                ('emp_created_at', models.DateTimeField(auto_now_add=True)),
                ('emp_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
