# Generated by Django 5.0.2 on 2024-02-19 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_data',
            name='emp_id',
            field=models.CharField(max_length=150),
        ),
    ]
